Import array basic method

In [6]:
import array as arr
## or use from array import *

val = arr.array('i',[1,2,3,4,5,6])
## then no need for arr.
#  val = array('i',[1,2,3,4,5,6])

for i in range(0,6):
# for in range(0,len(val))      
      print(val[i], end=" ")


## enchaced for loop

print('\n')

for x in val:
      print(x, end=" ")

1 2 3 4 5 6 

1 2 3 4 5 6 

Type Handling/Reverse

In [6]:
from array import *

val = array('i',[1,2,3,4,5,6])

print(val.typecode)

print('\n')

val.reverse()

for x in val:
      print(x, end=" ")

i


6 5 4 3 2 1 

CRUDs in Array

In [ ]:
from array import *

val = array('i',[1,2,3,4,5,6])

# Insert( Nothing gets deleted older elements shifts to right )

val.insert(1,37)

for x in val:
      print(x, end=" ")

print('\n')

# Append (last position)

val.append(82)

for x in val:
      print(x, end=" ")

print('\n')

# Replace/Override

val[0] = 10

for x in val:
      print(x, end=" ")

print('\n')

# Copy

copyArray = array(val.typecode,(x for x in val))

print("coppied array: ")

for x in copyArray:
      print(x, end=" ")

print('\n')

# Delete(if you dont give index last element will pop)

copyArray.pop(1)

print("Deleted index[1]: ")

for x in copyArray:
      print(x, end=" ")

print('\n')

# Remove (use it if you dont know the index but only the value)

copyArray.remove(82)

print("Removed element: ")

for x in copyArray:
      print(x, end=" ")

print('\n')
 

1 37 2 3 4 5 6 

1 37 2 3 4 5 6 82 

10 37 2 3 4 5 6 82 

coppied array: 
10 37 2 3 4 5 6 82 

Deleted index[1]: 
10 2 3 4 5 6 82 

Removed element: 
10 2 3 4 5 6 



## Slicing

In [ ]:
from array import *

val = array('i',[1,2,3,4,5,6,7,8,9,10])

abc = val[2:5] #start index (will include): end index will not

print("basic slicing: ")

for x in abc:
      print(x, end=" ")

print('\n')

#-----------------------------------------------------------------------

xyz = val[2:-3]

print("leaving certain no of elements from last:")

for x in xyz:
      print(x, end=" ")

print('\n')

#------------You want reverse the array with slicing--------------------

arr = val[::-1]

for x in arr:
      print(x, end=" ")

print('\n')


basic slicing: 
3 4 5 

leaving certain no of elements from last:
3 4 5 6 7 

10 9 8 7 6 5 4 3 2 1 



## User Input

In [ ]:
from array import *

arr = array('i',[])

n = int(input("Enter a number"))

for i in range(0,n):
      arr.append(int(input('Enter next input')))

for x in arr:
      print(x, end = " ")

print('\n')

#----------------Index Finding---------------------

a = array('i',[1,2,3,4,5,24,35,57,79,13])


1 2 3 4 5 24 35 57 79 13 



Index Finding

In [4]:
from array import *

a = array('i',[1,2,3,4,5,24,35,57,79,13])

i = arr.index(24)

print(i)

5


## Numpy

In [5]:
pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 8.0 MB/s  0:00:02m0:00:0100:01
Note: you may need to restart the kernel to use updated packages.


Basic

In [ ]:
from numpy import *

val = array([1,2,3,4,5,6.2,7,8.0,9.5,10,'a','b','c','d']) 
# hetrogenous arrays exist here
# val = array([1,2,3,4,5],float) custom type casting

for x in val:
      print(x, end =" ")

1 2 3 4 5 6.2 7 8.0 9.5 10 a b c d 

Different uses

In [ ]:
from numpy import *

# Suppose you wanna generate arthematics progression array

val = linspace(10,20,11) #start,end,division

for x in val:
      print(x, end =" ")

print('\n')

#---------------------------------------------------

val2 = arange(10,20,2) #start,end,plus (end will not be included here)

for x in val2:
      print(x, end =" ") 

print('\n')

#---------------------------------------------------

val3 = logspace(10,20,2) #start,end,plus 

for x in val3:
      print(x, end =" ") 

print('\n')

#---------------------------------------------------

val4 = zeros(10) #how many zeroes you need

for x in val4:
      print(x, end =" ") 

print('\n')

#---------------------------------------------------

val5 = full(10,5) #how many number, what no

for x in val5:
      print(x, end =" ") 



10.0 11.0 12.0 13.0 14.0 15.0 16.0 17.0 18.0 19.0 20.0 

10 12 14 16 18 

10000000000.0 1e+20 

0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 

5 5 5 5 5 5 5 5 5 5 

## Multidimensional Arrays in Numpy

In [47]:
from numpy import *

zero = array(10)
print(zero)

print('\n')

one = array([1,2,3,4,5])
print(one)

print('\n')

print("Two Dimensional Array:")
twoDimensional = array([[1,2,3],[4,5,6],[7,8,9]])
print(twoDimensional)

print('\n')

three_dimensional = array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print("Three Dimensional Array:")
print(three_dimensional)




10


[1 2 3 4 5]


Two Dimensional Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Three Dimensional Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
